apiVersion: dag.hamiltonai.dev/v1alpha1
kind: Guideline
metadata:
  name: golang
spec:
  instructions:
    - matching: ["**/*.go", "go.mod"]
      files:
        - code_style.md
        - patterns.md
        - setup.md
        - testing.md
        - e2e_testing.md

