apiVersion: dag.hamilton.io/v1alpha1
kind: Guideline
metadata:
  name: golang
spec:
  instructions:
    - matching: ["**/*.go"]
      files:
        - code_style.md
        - patterns.md
        - setup.md
        - testing.md
        - e2e_testing.md

